# Generated by Django 5.2 on 2025-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstappvarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
